feed/urls.py
from django.urls import path
from feed.views import create_post, home, PostDetailView, comment_create

urlpatterns = [
    path('', home, name='home'),
    path('post/create/', create_post, name='create_post'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/comment/', comment_create, name='create_comment'),

]

user_profile/urls.py
from django.urls import path

from user_profile.views import (ProfileDetailView, ProfileUpdateView,
                                login_view, logout_view, registration_view)

urlpatterns = [
    path('register/', registration_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('<slug:slug>/', ProfileDetailView.as_view(), name='detail'),
    path('<slug:slug>/edit/', ProfileUpdateView.as_view(), name='update'),
]

your_space/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('feed.urls', 'feed'), namespace='feed')),
    path('', include(('user_profile.urls', 'profile'), namespace='profile')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

class TimeStampModel(models.Model):
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        abstract = True

feed/models.py
from django.db import models
from django.contrib.auth import get_user_model

from common.models import TimeStampModel

User = get_user_model()

class Post(TimeStampModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    likers = models.ManyToManyField(User, related_name='liked_posts')

    
    def __str__(self):
        return f"{self.user.username} - {self.created_date}"
    
class Comment(TimeStampModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    
    def __str__(self):
        return f"{self.user.username} - {self.created_date}"

user_profile/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class Profile(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    first_name = models.CharField(max_length=50,blank=True, null=True)
    last_name = models.CharField(max_length=50,blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile/')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    friends = models.ManyToManyField(User, blank= True, related_name='friends')
    bio_info= models.TextField(max_length=300, blank=True, null=True)

    
    def __str__(self):
        return f"{self.user.username}"
    

feed/forms.py
from django import forms
from feed.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'image']

user_profile/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "first_name",
            "last_name",
            "profile_picture",
            "gender",
            "bio_info",
        ]

feed/views.py
from django.shortcuts import render,redirect
from django.views.generic import DetailView
from feed.forms import PostForm
from .models import Post, Comment

def home(request):
    posts = Post.objects.all().order_by('-created_date')
    context = {'posts': posts}
    return render(request, 'feed/home.html', context)


def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('feed:home')  # Adjust the URL name as per your setup
    else:
        form = PostForm()
    
    return redirect('feed:home')


class PostDetailView(DetailView):
    model = Post
    template_name = 'feed/post_detail.html'
    context_object_name = 'post'
    
def comment_create(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        content = request.POST['content']
        Comment.objects.create(post=post, user=request.user, content=content)
    return redirect('feed:post_detail', pk=pk)

user_profile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from user_profile.forms import ProfileForm
from user_profile.models import Profile
from django.views import View
from feed.models import Post

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('feed:home')
    else:
        form = AuthenticationForm()
    return render(request, 'auth/login.html', {'form': form})

def registration_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            return redirect('profile:login')
    else:
        form = UserCreationForm()
    return render(request, 'auth/register.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('feed:home') 


class ProfileDetailView(View):
    def get(self, request, slug):
        profile = get_object_or_404(Profile, user__username=slug)
        posts = Post.objects.filter(user__username=slug)
        context = {
            'profile': profile,
            'posts': posts,
            'own_profile': request.user == profile.user
        }
        return render(request, 'user_profile/detail.html', context)
    
    
class ProfileUpdateView(View):
    def get(self, request, slug):
        profile = get_object_or_404(Profile, user__username=slug)
        form = ProfileForm(instance=profile)
        context = {
            'form': form
        }
        return render(request, 'user_profile/update.html', context)

    def post(self, request, slug):
        profile = get_object_or_404(Profile, user__username=slug)
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile:detail', slug=slug)
        return render(request, 'user_profile/update.html', {'form': form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Your Space</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
<body>
    <header>
        <div class="logo">
            <a href="{% url 'feed:home' %}">
                <img src="{% static 'images/logo.png' %}" alt="Logo">
            </a>
            <h1 class="site-title">Your Space</h1>
        </div>
        <div class="user-info">
            {% if user.is_authenticated %}
                <div class="profile-picture">
                    <a href="{% url 'profile:detail' slug=user.username %}">
                        {% if user.profile.profile_picture %}
                            <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture">
                        {% else %}
                            {% if user.profile.gender == 'F' %}
                                <img src="{% static 'images/avatar-female.png' %}" alt="Default Profile Picture">
                            {% else %}
                                <img src="{% static 'images/avatar-male.png' %}" alt="Default Profile Picture">
                            {% endif %}
                        {% endif %}
                    </a>
                </div>
                <div class="user-actions">
                    <a href="{% url 'profile:detail' slug=user.username %}" class="username">{{ user.username }}</a>
                    <a href="{% url 'profile:logout' %}" class="btn btn-sign-out">Sign Out</a>
                </div>
            {% else %}
                <div class="user-actions">
                    <a href="{% url 'profile:login' %}" class="btn btn-login">Login</a>
                    <a href="{% url 'profile:register' %}" class="btn btn-register">Register</a>
                </div>
            {% endif %}
        </div>
    </header>
    
    <main>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
</body>
</html>

templates/feed/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="feed">
    {% if request.user.is_authenticated %}
    <div class="post-upload">
      <form action="{% url 'feed:create_post' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <textarea name="content" placeholder="What's on your mind?" class="post-upload-content"></textarea>
        <div class="post-upload-options">
          <input type="file" name="image" class="post-upload-image" id="image-upload">
          <label for="image-upload" class="btn btn-upload">Choose Image</label>
          <span id="image-name"></span>
          <button type="submit" class="btn btn-submit">Post</button>
        </div>
      </form>
    </div>
    {% endif %}
    {% for post in posts %}
      <div class="post" href="{% url 'feed:post_detail' post.id %}">
        <div class="post-header">
          <div class="post-author">
            <a href="{% url 'profile:detail' slug=post.user.username %}">
                {% if post.user.profile.profile_picture %}
                    <img src="{{ post.user.profile.profile_picture.url }}" alt="Profile Picture">
                {% else %}
                    {% if post.user.profile.gender == 'F' %}
                        <img src="{% static 'images/avatar-female.png' %}" alt="Default Profile Picture">
                    {% else %}
                        <img src="{% static 'images/avatar-male.png' %}" alt="Default Profile Picture">
                    {% endif %}
                {% endif %}
            <p>{{ post.user.username }}</p>
            </a>
          </div>
          <div class="post-actions">
            <a href="#" class="action-icon"><i class="far fa-heart"></i></a>
            <a href="#" class="action-icon"><i class="far fa-comment"></i></a>
          </div> 
          <a href="{% url 'feed:post_detail' post.id %}" class="btn-more">More</a>
        </div>
        <div class="post-body">
          <h3>{{ post.title }}</h3>
          <p>{{ post.content }}</p>
          {% if post.image %}
            <div class="post-image">
              <img src="{{ post.image.url }}" alt="Post Image">
            </div>
          {% endif %}
        </div>
        <div class="post-footer">
          <div class="post-info">
            <p class="likes"><i class="far fa-heart"></i> {{ post.likers.count }} likes</p>
            <p class="comments"><i class="far fa-comment"></i> {{ post.comments.count }} comments</p>
          </div>
        </div>
        <div class="comment-list">
          {% for comment in post.comments.all %}
            <div class="comment">
              <div class="comment-author">
                <a href="{% url 'profile:detail' slug=comment.user.username %}">
                  {% if comment.user.profile.profile_picture %}
                    <img src="{{ comment.user.profile.profile_picture.url }}" alt="Profile Picture">
                  {% else %}
                    {% if comment.user.profile.gender == 'F' %}
                      <img src="{% static 'images/avatar-female.png' %}" alt="Default Profile Picture">
                    {% else %}
                      <img src="{% static 'images/avatar-male.png' %}" alt="Default Profile Picture">
                    {% endif %}
                  {% endif %}
                  <p>{{ comment.user.username }}</p>
                </a>
              </div>
              <div class="comment-content">
                <p>{{ comment.content }}</p>
              </div>
            </div>
          {% empty %}
            <p>No comments yet.</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/feed/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="post">
    <div class="post-header">
      <div class="post-author">
        <a href="{% url 'profile:detail' slug=post.user.username %}">
          {% if post.user.profile.profile_picture %}
            <img src="{{ post.user.profile.profile_picture.url }}" alt="Profile Picture">
          {% else %}
            {% if post.user.profile.gender == 'F' %}
              <img src="{% static 'images/avatar-female.png' %}" alt="Default Profile Picture">
            {% else %}
              <img src="{% static 'images/avatar-male.png' %}" alt="Default Profile Picture">
            {% endif %}
          {% endif %}
          <p>{{ post.user.username }}</p>
        </a>
      </div>
      <div class="post-actions">
        <a href="#" class="action-icon"><i class="far fa-heart"></i></a>
        <a href="#" class="action-icon"><i class="far fa-comment"></i></a>
      </div>
    </div>
    <div class="post-body">
      <h3>{{ post.title }}</h3>
      <p>{{ post.content }}</p>
      {% if post.image %}
        <div class="post-image">
          <img src="{{ post.image.url }}" alt="Post Image">
        </div>
      {% endif %}
    </div>
    <div class="post-footer">
      <div class="post-info">
        <p class="likes"><i class="far fa-heart"></i> {{ post.likers.count }} likes</p>
        <p class="comments"><i class="far fa-comment"></i> {{ post.comments.count }} comments</p>
      </div>
    </div>
    <div class="comments">
      <div class="comment-list">
        <div class="comment-section">
            <h2>Add a Comment</h2>
            <form action="{% url 'feed:create_comment' post.id %}" method="POST" class="comment-form">
              {% csrf_token %}
              <div class="form-row">
                <textarea name="content" placeholder="Write your comment..." required></textarea>
              </div>
              <div class="form-row">
                <button type="submit" class="btn btn-comment">Post Comment</button>
              </div>
            </form>
          </div>
        {% for comment in post.comments.all %}
          <div class="comment">
            <div class="comment-author">
              <a href="{% url 'profile:detail' slug=comment.user.username %}">
                {% if comment.user.profile.profile_picture %}
                  <img src="{{ comment.user.profile.profile_picture.url }}" alt="Profile Picture">
                {% else %}
                  {% if comment.user.profile.gender == 'F' %}
                    <img src="{% static 'images/avatar-female.png' %}" alt="Default Profile Picture">
                  {% else %}
                    <img src="{% static 'images/avatar-male.png' %}" alt="Default Profile Picture">
                  {% endif %}
                {% endif %}
                <p>{{ comment.user.username }}</p>
              </a>
            </div>
            <div class="comment-content">
              <p>{{ comment.content }}</p>
            </div>
          </div>
        {% empty %}
          <p>No comments yet.</p>
        {% endfor %}
      </div>
    </div>
  </div>
  </div>
{% endblock %}

templates/user_profile/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="profile-container">
    <div class="profile-picture-img">
      {% if profile.profile_picture %}
        <img src="{{ profile.profile_picture.url }}" alt="Profile Picture">
      {% else %}
        {% if user.profile.gender == 'F' %}
          <img src="{% static 'images/avatar-female.png' %}" alt="Default Profile Picture">
        {% else %}
          <img src="{% static 'images/avatar-male.png' %}" alt="Default Profile Picture">
        {% endif %}
      {% endif %}
    </div>
    <div class="profile-details">
      <h1>{{ profile.user.username }}'s Profile</h1>
      <p>First Name: {% if profile.first_name %}{{ profile.first_name }}{% else %}&nbsp;{% endif %}</p>
      <p>Last Name: {% if profile.last_name %}{{ profile.last_name }}{% else %}&nbsp;{% endif %}</p>
      <p>Gender: {{ profile.get_gender_display }}</p>
      <p>Bio Info: {% if profile.bio_info %}{{ profile.bio_info }}{% else %}&nbsp;{% endif %}</p>
      {% if own_profile %}
        <a href="{% url 'profile:update' slug=profile.user.username %}" class="btn btn-edit">Edit Profile</a>
      {% endif %}
    </div>
  </div>

  <div class="user-posts">
    <h2>{{ profile.user.username }}'s Posts</h2>

    {% for post in posts %}
    <div class="post" href="{% url 'feed:post_detail' post.id %}">
      <div class="post-header">
        <div class="post-author">
          <a href="{% url 'profile:detail' slug=post.user.username %}">
              {% if post.user.profile.profile_picture %}
                  <img src="{{ post.user.profile.profile_picture.url }}" alt="Profile Picture">
              {% else %}
                  {% if post.user.profile.gender == 'F' %}
                      <img src="{% static 'images/avatar-female.png' %}" alt="Default Profile Picture">
                  {% else %}
                      <img src="{% static 'images/avatar-male.png' %}" alt="Default Profile Picture">
                  {% endif %}
              {% endif %}
          <p>{{ post.user.username }}</p>
          </a>
        </div>
        <div class="post-actions">
          <a href="#" class="action-icon"><i class="far fa-heart"></i></a>
          <a href="#" class="action-icon"><i class="far fa-comment"></i></a>
        </div> 
        <a href="{% url 'feed:post_detail' post.id %}" class="btn-more">More</a>
      </div>
      <div class="post-body">
        <h3>{{ post.title }}</h3>
        <p>{{ post.content }}</p>
        {% if post.image %}
          <div class="post-image">
            <img src="{{ post.image.url }}" alt="Post Image">
          </div>
        {% endif %}
      </div>
      <div class="post-footer">
        <div class="post-info">
          <p class="likes"><i class="far fa-heart"></i> {{ post.likers.count }} likes</p>
          <p class="comments"><i class="far fa-comment"></i> {{ post.comments.count }} comments</p>
        </div>
      </div>
      <div class="comment-list">
        {% for comment in post.comments.all %}
          <div class="comment">
            <div class="comment-author">
              <a href="{% url 'profile:detail' slug=comment.user.username %}">
                {% if comment.user.profile.profile_picture %}
                  <img src="{{ comment.user.profile.profile_picture.url }}" alt="Profile Picture">
                {% else %}
                  {% if comment.user.profile.gender == 'F' %}
                    <img src="{% static 'images/avatar-female.png' %}" alt="Default Profile Picture">
                  {% else %}
                    <img src="{% static 'images/avatar-male.png' %}" alt="Default Profile Picture">
                  {% endif %}
                {% endif %}
                <p>{{ comment.user.username }}</p>
              </a>
            </div>
            <div class="comment-content">
              <p>{{ comment.content }}</p>
            </div>
          </div>
        {% empty %}
          <p>No comments yet.</p>
        {% endfor %}
      </div>
    </div>
    {% empty %}
      <p>No posts yet.</p>
    {% endfor %}
  </div>
{% endblock %}

templates/user_profile/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>Edit Profile</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}